# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2b380cfcd67fb85eda612cc32ab329ed"
name = "old-3d-temp"
handle = "old-3d-temp"
application_url = "https://stolen-pam-winner-kijiji.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hellostorexyz.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_online_store_pages,read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://stolen-pam-winner-kijiji.trycloudflare.com/auth/callback",
  "https://stolen-pam-winner-kijiji.trycloudflare.com/auth/shopify/callback",
  "https://stolen-pam-winner-kijiji.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
